### ISSUE TITLE
4sq_cc-1.1.shp resource.

### ISSUE THREAD

**Issue by jeffsteinmetz** [foursquare/twofishes#35]
I have read the docs, regarding shape files not being included in the distribution.
I see in some .shp files in "resources" at:
https://github.com/foursquare/twofishes/tree/master/quadtree/src/main

I was curious what the files in the "resources" used for?
I see in the documentation the following guidelines:
 - take the resulting shapefile (the shp, shx, cpg, dbf) and put them in data/private/polygons

I was a little unclear on how this directory was used, since the data/private/polygons directory is in the source, and not the index pointed at by --hfile_basepath

Does the index need to be rebuilt after placing these in data/private/polygons?

running a reverseGeo query such as:
localhost:8081/?ll=40.74,-74.0

results in:

java.io.FileNotFoundException: Could not find 4sq_cc-1.1.shp resource.  Check the classpath/deps?
com.foursquare.geo.quadtree.CountryRevGeo$$anonfun$loadResource$1.apply(CountryCodeRevGeo.scala:13)

**Comment by rahulpratapm** [comment]
That's explained at length here:
https://github.com/foursquare/twofishes/blob/master/docs/auxiliary_features_and_polygons.md
