### ISSUE TITLE
Some regions / counrties are not recognized

### ISSUE THREAD

**Issue by dkling** [foursquare/twofishes#36]
I'm using current `twofishes` version from GitHub, branch `master`. I imported data for the **whole word** (`./parse.py -w ...`).

If I'm querying for following counties/ regions, I don't receive any meaningful data:

1) "Deutschland" (German for "Germany"), NB I'm using `lang=de`:

**Query**: http://_MY TWOFISHES SERVER, WITH DATA FOR THE WHOLE WORLD IMPORTED_:8081/?autocomplete=true&query=Deutschland&lang=de&maxInterpretations=5

**Result**:

```
{"interpretations":[{"what":"","where":"deutschland","feature":{"cc":"AT","geometry":{"center":{"lat":46.81528,"lng":15.22222},"bounds":{"ne":{"lat":46.8197975159,"lng":15.2324151993},"sw":{"lat":46.805934906,"lng":15.1987686157}}},"name":"Lonč","displayName":"Lonč, Österreich","woeType":7,"ids":[{"source":"geonameid","id":"2781023"},{"source":"woeid","id":"548215"},{"source":"woeid","id":"12674916"}],"names":[{"name":"Deutschlandsberg","lang":"en","flags":[1]}],"highlightedName":"<b>Deutschland</b>sberg, Österreich","matchedName":"Deutschlandsberg, Österreich","id":"geonameid:2781023","attributes":{"population":8049},"longId":"72057594040708959","longIds":["72057594045801283"],"parentIds":["72057594040710049","72057594040692517","72057594040708958","72057594045801283"]}},{"what":"","where":"deutschland","feature":{"cc":"AQ","geometry":{"center":{"lat":-73.5,"lng":-29.83333}},"name":"Deutschland Canyon","displayName":"Deutschland Canyon","woeType":0,"ids":[{"source":"geonameid","id":"6639176"}],"names":[{"name":"Deutschland Canyon","lang":"en","flags":[1]}],"highlightedName":"<b>Deutschland</b> Canyon","matchedName":"Deutschland Canyon","id":"geonameid:6639176","attributes":{"population":0},"longId":"72057594044567112","parentIds":["72057594044625109"]}}]}
```

**Expected results**:
The results for the country "Germany", as displayed here: http://www.geonames.org/2921044/federal-republic-of-germany.html

2) "Südtirol" (aka by its italian name - "Trentino-Alto Adige" - is an region in Northern Italy):

**Query:**
http://_MY TWOFISHES SERVER, WITH DATA FOR THE WHOLE WORLD IMPORTED_:8081/?autocomplete=true&query=Südtirol&lang=de&maxInterpretations=5

**Results:**

```
{"interpretations":[]}
```

**Expected results**: a non-empty result with coordinates for this region - http://www.geonames.org/3165244/trentino-alto-adige.html

**Comment by aggied** [comment]
@blackmad I am running the prebuilt for now while I test out twofishes. Can you verify if this "hack" was ever removed? I'm running prebuilt server binary `version 0.84.9`.

**Comment by parkan** [comment]
@aggied: I don't believe this was removed, the above instructions should still work, more or less
