### ISSUE TITLE
Are longIds canonical?

### ISSUE THREAD

**Issue by heyman** [foursquare/twofishes#47]
Hi!

First of all, thanks for a great product!

I'm wondering if one can consider Twofishes' longIds to be canonical, i.e. they won't change in the future, or between index rebuilds?

I looked at the documentation, but couldn't find any info on this, which I assume is because responses aren't documented yet.

Thanks!

**Comment by rahulpratapm** [comment]
Those are not guaranteed to be stable since they're just sequentially assigned as they're created.
