### ISSUE TITLE
Release management / stable version

### ISSUE THREAD

**Issue by masone** [foursquare/twofishes#56]
We are working with the precompiled binary that you provide on http://twofishes.net. We ran into an issue with `too many tokens` which seems to be fixed now. And I'm sure you did a lot of improvements since 2013.

Are we supposed to build master? Is it always stable or how do I get the most recent stable version? It seems like you're already doing [versioning](https://github.com/foursquare/twofishes/blob/5200354e26059dc8760041ae6ae4e04755bf0745/project/build.properties#L1) internally, but it's not represented in the repository (eg. with branches/tags).

Am I missing something or may I suggest to start versioning this repos versions with [github releases](https://github.com/blog/1547-release-your-software)? Or alternatively use tags for versioning and provide a Changelog manually. This would help external users of your great project a lot when maintaining an installation.

**Comment by rahulpratapm** [comment]
Hi Christian,

You're right. This is something we've been meaning to get to. Arkadiy is already tracking this via https://github.com/foursquare/twofishes/issues/55.

Rahul.

**Comment by masone** [comment]
Thanks for your response Rahul

**Comment by rahulpratapm** [comment]
Should've updated this a long time ago. We're doing this now.
