### ISSUE TITLE
Warmup Period?

### ISSUE THREAD

**Issue by aggied** [foursquare/twofishes#60]
New to the repo -- great product! Very happy to see the prebuilt indexes for download. I am testing out the most recent prebuilt server/index (3-5/10-2015) with this command: 

     java -Xms2560M -Xmx2560M -Xmn200M -XX:+HeapDumpOnOutOfMemoryError  -jar server-assembly-0.84.9.jar --hfile_basepath 2015-03-05-20-05-30.753698/ &> twofishes_log.txt

All queries are SLOW -- like 10s + -- for a long while. At some point it's like the app warms up and response time is nice. I left it running on my machine overnight and in the morning it was fast.... 

thoughts? Does it have something to do w/ my config? The fact that it's prebuilt?

**Comment by rahulpratapm** [comment]
It isn't normal for initial requests to take that long. What kind of
hardware are you running the server on?

Meanwhile, you can pass the --warmup argument to serve.py and it will be
all good when it starts. Again, depending on your hardware, the warmup
itself could take a while.

Rahul.

**Comment by aggied** [comment]
Intel Xeon CPU, 5110 @ 1.60GHz, 4.00GB RAM. Here's the top memory consuming processes:

![image](https://cloud.githubusercontent.com/assets/4122815/7325495/96a6074a-ea8c-11e4-8853-7a47f1b366ce.png)

Is there a better way to start the prebuilt? I should also note that i've tried this on two different machines -- one eventually "warms up" and the other doesn't.

**Comment by parkan** [comment]
Have you tried passing `--warmup true`?

**Comment by aggied** [comment]
@parkan I also missed it. Thanks for pointing that out! I think I mostly blame my lack of understanding on what the `warmup` does... the second machine that was never "warming up" all of the sudden woke up. What exactly is warmup? Does it run a bunch of queries? Is it a time thing? 

@parkan for clarification, can I pass `--warmup true` to the prebuilt? I'm not even calling `serve.py` as I'm just running the command I mentioned in the original question on the prebuilt.

**Comment by parkan** [comment]
`--warmup true` will run a set of predetermined queries, take a look at https://github.com/foursquare/twofishes/blob/master/server/src/main/scala/GeocodeServer.scala#L144

You should be able to pass that directly to the above invocation

**Comment by aggied** [comment]
Started the prebuilt with the following command and the warmup seemed to work great. Thanks!

`````
java -Xms2560M -Xmx2560M -Xmn200M -XX:+HeapDumpOnOutOfMemoryError  -jar server-assembly-0.84.9.jar --warmup true --hfile_basepath 2015-03-05-20-05-30.753698/ &
`````

**Comment by rburton** [comment]
Just curious, how long did the warmup take? I'm running an EC2 m3.large and it's taking over 15 minutes. I'm trying to find out what hardware do I need to run this application on. I thought m1.medium might have worked, but the requests were slow (w/o a warmup). I'm still waiting on the warmup to finish :)

Cheers,

**Comment by rahulpratapm** [comment]
The warmup does 3 rounds of the following:
10000 forward geocodes
10000 reverse geocodes
10000 id lookups

So that's 90000 queries total, although the counters reset for each round. It should print progress every 1000 queries. How far does it seem to have come?

Our production warmups take 3-4 min but our production machines are also much much larger than ec2 m3.large.

**Comment by rburton** [comment]
After 30 minutes or so it seemed to finish. No exceptions, but I can't make requests to the service. 

I see a ton of the following:

c.foursquare.twofishes.MapFileInput - reading key 'geonameid:1269750' from index 'features' took 1977 milliseconds. valueOpt is Some(5011) bytes long

I was hoping to be able to use a m1.medium until I have more of a load then I would get a bigger box. Locally on my Mac, I don't need a warm up and it works well.

**Comment by rahulpratapm** [comment]
Those messages are expected in large numbers during warmup. They should be fewer and farther between afterwards.

How are you trying to make requests to the service? Are you making http requests on the thrift port, for instance?

**Comment by rburton** [comment]
That's the interesting thing - the durations hover around 1.2 seconds. When there's no warmup, I'm seeing a lot of I/O.

When I access the application, I'm hitting port 8081 using curl. 

Below you'll see the last 6 or so lines:

16:15:02.574 [pool-geocoder-thread-15] INFO  c.foursquare.twofishes.MapFileInput - reading key 'geonameid:1210997' from index 'features' took 1864 milliseconds. valueOpt is Some(7115) bytes long
16:15:02.574 [pool-geocoder-thread-5] INFO  c.foursquare.twofishes.MapFileInput - reading key 'geonameid:1269750' from index 'features' took 1865 milliseconds. valueOpt is Some(5011) bytes long
16:15:04.613 [pool-geocoder-thread-22] INFO  c.foursquare.twofishes.MapFileInput - reading key 'geonameid:1269750' from index 'features' took 1763 milliseconds. valueOpt is Some(5011) bytes long
16:15:04.614 [pool-geocoder-thread-2] INFO  c.foursquare.twofishes.MapFileInput - reading key 'geonameid:1269750' from index 'features' took 1744 milliseconds. valueOpt is Some(5011) bytes long
16:15:04.626 [pool-geocoder-thread-5] INFO  c.foursquare.twofishes.MapFileInput - reading key 'geonameid:1269750' from index 'features' took 1748 milliseconds. valueOpt is Some(5011) bytes long
16:15:04.707 [pool-geocoder-thread-17] INFO  c.foursquare.twofishes.MapFileInput - reading key 'geonameid:1814991' from index 'features' took 1766 milliseconds. valueOpt is Some(6598) bytes long
