### ISSUE TITLE
Syntax Error when trying to use the geocoder debug interface

### ISSUE THREAD

**Issue by fullofcaffeine** [foursquare/twofishes#63]
The error:

![wsbsz1wycaha9rupyupilq4nxnauqdiayxymgmqnugc](https://cloud.githubusercontent.com/assets/81248/7354048/03e69ac4-ecde-11e4-823f-dec8a24856a4.png)

```
ERROR: 
parsererror 
SyntaxError: Unexpected token <
probably want to debug @ http://localhost:8082/?debug=1&responseIncludes=EVERYTHING,WKT_GEOMETRY_SIMPLIFIED,WKB_GEOMETRY_SIMPLIFIED&query=
```

I can't see anything in the logs. Any ideas?

**Comment by rahulpratapm** [comment]
Seems like you're using the thrift port. Try localhost:8083 :)

Rahul.

**Comment by fullofcaffeine** [comment]
Hi @rahulpratapm, thank you for the reply!

Port 8083 gives me:

![screenshot 2015-04-27 17 06 59](https://cloud.githubusercontent.com/assets/81248/7359042/ea4bb186-ecff-11e4-9322-4c375f6d295a.png)

I'm starting the server with the following command:

```java -jar server/target/scala-2.10/server-assembly-0.84.11.jar --hfile_basepath indexes/2015-04-27-22-00-02.601303/```

The server process says it's listening at port 8082:

```INFO: Admin HTTP interface started on port 8082.```

I'm confused.

**Comment by rahulpratapm** [comment]
Oh, in that case you should be trying 8081.

Rahul.

**Comment by fullofcaffeine** [comment]
Great! Works now. Thank you!

**Comment by fullofcaffeine** [comment]
Btw, may I ask why it says "listening on port 8082" but the actual port should be that port-1?

**Comment by parkan** [comment]
We should either document this better or prevent ostrich from serving the static files

**Comment by rahulpratapm** [comment]
I think we should take the burden of doing all this port arithmetic off
users altogether. So, let's make our logging messages clearer AND prevent
ostrich from serving the static files.

Rahul.
