### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by fullofcaffeine** [foursquare/twofishes#65]
First of all, thank you for making this open source! I came from this code from quattroshapes*[0]. I'm searching for a relatively complete database of neighborhoods mulipolygons for at least the major cities around the world. From what I've read in the README for quattroshapes, it does have the data I need.

However, it looks like TwoFishes might be the best way to get started and output the geojson data I need. I'm yet to have it running locally without errors, but I could play with the demo, and it found the neighborhoods for almost all the cities I've tried.

A couple of things are not clear, yet. I'd be great if one of the developers could shed some light on them :) I'd be greatful!

1) To fetch neighborhood geojson data (with polygon boundary information) from names, is the data fetched by `download_world.sh` enough?
2) From what I've read in the README, it looks like the reverse - getting the neighborhood data from lat/long - would require me to import additional data. Is it when I need to import quattroshapes imported into Postgres/PostGIS to finally get a shapefile?
3) Looks like the API is based off Thrift. Do you keep the API documentation anywhere? How should I consume the API?
4) Curious: I assume you guys using this as a microservice inside foursquare as a way to query polygon data for the foursquare app? Is that right? (It's nice and useful to know the more specific use cases).

*[0] http://quattroshapes.com/

Thanks,

-- Marcelo

**Comment by fullofcaffeine** [comment]
I managed to get it running locally, yay!

So, expanding on question 2:

2.1) I can find the neighborhood by name: 

* https://www.dropbox.com/s/nvgp98sqyjd0qjj/Screenshot%202015-04-27%2017.27.26.png?dl=0

However, the current live demo has a different shape for the boundaries for the same neighborhood:

* https://www.dropbox.com/s/we265782u6vmysx/Screenshot%202015-04-27%2017.28.20.png?dl=0

Why?

2.2) Expanding on this even further. I have tried to get the same polygon data from Maponics, and I get:

* https://www.dropbox.com/s/bapio8yi5jfzgbe/Screenshot%202015-04-27%2016.53.40.png?dl=0

And Gmaps shows a slightly different polygon (a more exact representation, it seems):

*  https://www.dropbox.com/s/kvlavz4yoq2p41l/Screenshot%202015-04-27%2016.39.45.png?dl=0

Does anyone know why?

**Comment by rahulpratapm** [comment]
Inline.

On Mon, Apr 27, 2015 at 6:18 PM, Marcelo de Moraes Serpa <
notifications@github.com> wrote:

> First of all, thank you for making this open source! I came from this code
> from quattroshapes*[0]. I'm searching for a relatively complete database of
> neighborhoods mulipolygons for at least the major cities around the world.
> From what I've read in the README for quattroshapes, it does have the data
> I need.
>
> However, it looks like TwoFishes might be the best way to get started and
> output the geojson data I need. I'm yet to have it running locally without
> errors, but I could play with the demo, and it found the neighborhoods for
> almost all the cities I've tried.
>
> A couple of things are not clear, yet. I'd be great if one of the
> developers could shed some light on them :) I'd be greatful!
>
> 1) To fetch neighborhood geojson data (with polygon boundary information)
> from names, is the data fetched by download_world.sh enough?
>
This downloads free geonames data. You still need to download additional
polygon sources such as quattroshapes (or Maponics, for that matter).

> 2) From what I've read in the README, it looks like the reverse - getting
> the neighborhood data from lat/long - would require me to import additional
> data. Is there when quattroshapes needs to be imported into Postgres with
> PostGIS?
>
Pass parse.py the --output_revgeo_index arg if you want to build a reverse
geocode index and --output_prefix_index if you want to build an
autocomplete index.

> 3) Looks like the API is based off Thrift. Do you keep the API
> documentation anywhere? How should I consume the API?
>
https://github.com/foursquare/twofishes/blob/master/docs/twofishes_requests.md


> 4) Curious: I assume you guys using this as a microservice inside
> foursquare as a way to query polygon data for the foursquare app? Is that
> right?
>
Yes. We use twofishes to power forward (including autocomplete) and reverse
geocodes.

**Comment by rahulpratapm** [comment]
Inline.

On Mon, Apr 27, 2015 at 6:29 PM, Marcelo de Moraes Serpa <
notifications@github.com> wrote:

> I managed to get it running locally, yay!
>
> So, expanding on question 2:
>
> 2.1) I can find the neighborhood by name:
>
>    -
>    https://www.dropbox.com/s/nvgp98sqyjd0qjj/Screenshot%202015-04-27%2017.27.26.png?dl=0
>
> However, the current live demo has a different shape for the boundaries
> for the same neighborhood:
>
>    -
>    https://www.dropbox.com/s/we265782u6vmysx/Screenshot%202015-04-27%2017.28.20.png?dl=0
>
> Why?
>
If you're using the prebuilt indexes locally, they should ideally be the
same. If you built your own, yes, you need to download additional polygon
sources.

> 2.2) Expanding on this even further. I have tried to get the same polygon
> data from Maponics, and I get:
>
>    -
>    https://www.dropbox.com/s/bapio8yi5jfzgbe/Screenshot%202015-04-27%2016.53.40.png?dl=0
>
> And Gmaps shows a slightly different polygon (a more exact representation,
> it seems):
>
>    -
>    https://www.dropbox.com/s/kvlavz4yoq2p41l/Screenshot%202015-04-27%2016.39.45.png?dl=0
>
> Does anyone know why?
>
Well, neighborhood shapes are rarely universally agreed upon fact.
Different providers use different sources and then add their own layers of
validation and additional processing. So this difference is expected with
most neighborhoods around the world.
