### ISSUE TITLE
Some geonames seem to be missing

### ISSUE THREAD

**Issue by aggied** [foursquare/twofishes#67]
I have a need to use twofishes to pull further information (polygons mostly) from an existing collection of geonamesIds. I found that I can query them with something like 
     
     ?slug=geonameid:4709696&responseIncludes=PARENTS,WKT_GEOMETRY_SIMPLIFIED

Only problem is some of them seem to be missing... can anyone share some light on this? Is twofishes supposed to have all of geonames in there? If so, perhaps my geonames ids are out of date? Or would the twofishes index be more likely to be out of date? 

For context, I'm using the latest prebuilt server and binary.

**Comment by aggied** [comment]
Perhaps I'll answer my own question -- but still would value any input on the topic! Correct me if I'm wrong here:

Geonames has quite a diverse set of entities, many of them not being political places. `geonameid:4709696` for example is Maverick Stadium in Texas. Twofishes probably does not have this type of data in there as it doesn't really fit. 

Thoughts anyone? Sound right?

**Comment by parkan** [comment]
Take a look at `shouldParseBuildings` param here: https://github.com/foursquare/twofishes/blob/master/indexer/src/main/scala/importers/geonames/GeonamesImporterConfig.scala#L6

**Comment by aggied** [comment]
So I admit I haven't yet taken the time to build yet -- I've just been running the prebuilt to try things out. @parkan would you mind shedding some light on `shouldParseBulidings`? Does this mean all geonames are included in the index? Just buildings, or terrain as well? Lastly -- where would a guy get a nice collection of building polygons to import?

**Comment by parkan** [comment]
"Building" here is taken to mean a rather broad category of points of interest, more or less equivalent to `S` here: http://www.geonames.org/export/codes.html

These features are not included in the index by default, though I suppose you can build one with them included. There are a bunch of other feature categories excluded on an ad-hoc basis, like wells and historical ruins. The geonames taxonomy is huge and full of weird things!

I can't advise you on building polygons, but depending on your application you may be able to use OSM or municipal data.

**Comment by aggied** [comment]
Thanks for the input. I'm getting what I need for now without parsing out buildings, but will add that in the future.
