### ISSUE TITLE
Resolution of "Porto"

### ISSUE THREAD

**Issue by alixaxel** [foursquare/twofishes#74]
When I search for Porto:

 - http://demo.twofishes.net/static/geocoder.html?query=Porto

Why does twofishes resolve to a city/town in Brazil with a population of 83,927 and with "Santana" as its original name instead of the [*"original"* city of Porto](https://en.wikipedia.org/wiki/Porto), in **Port**ugal, with a population of 249,633?

 - http://demo.twofishes.net/static/geocoder.html?query=Porto,%20PT

I would assume Porto (Portugal) would rank higher for "Porto" lookups in every aspect, but apparently not.

Can someone clarify what is going on behind the scenes?

**Comment by rahulpratapm** [comment]
Notice the higher manual boost that Porto BR receives that nudges it past Porto PT. I agree this doesn't make sense, though.

These manual boosts were generated a long time back using some measure of Foursquare venue density and checkin volume. We're currently working on regenerating the manual boosts as we've found them to be somewhat arbitrary and hard to reason about.

**Comment by alixaxel** [comment]
@rahulpratapm Ah now it makes more sense, thanks for that. :)

Question: is there a way I can build the indexes without taking into account these manual boosts?

**Comment by rahulpratapm** [comment]
I think I screwed up while building the public index and included private/boosts.txt where I shouldn't have.

There's more information on how the data directory is laid out at https://github.com/foursquare/twofishes/blob/master/docs/twofishes_inputs.md and https://github.com/foursquare/twofishes/blob/master/docs/auxiliary_features_and_polygons.md

Follow the instructions at
https://github.com/foursquare/twofishes#first-time-setup and
https://github.com/foursquare/twofishes#data-import
to build your own index.
