### ISSUE TITLE
secure deployment?

### ISSUE THREAD

**Issue by canebat** [foursquare/twofishes#83]
I didn't see any documentation on what good practices would be for deploying onto a live server. 

I have an application that queries on `localhost:8081` to get geocoding results, and I was thinking of putting Nginx in front of everything and doing a reverse-proxy, all on a Ubuntu server.

I'm booting twofishes with (as written in the docs):

    java -jar server-assembly-0.81.9.jar --hfile_basepath INDEX_DIRECTORY

Are there any security concerns or specific configurations that are recommended for deployment?

**Comment by rahulpratapm** [comment]
I guess we haven't really put too much thought into trying to document the general deployment case, if there is such a thing. At Foursquare, our geocoder machines are not accessible from the open internet, only via internal RPC and private API endpoints.

Maybe @jparise might have something to add about how they deploy twofishes at Pinterest and @blackmad about Twitter and also the public facing demo at twofishes.net.

I will say, though, that I see no particular security concerns with your specific invocation. Should you want to enable hotfixes later, you probably don't want to enable private endpoints with this configuration (as that will allow anyone to DoS your server by repeatedly reloading the hotfix store). See https://github.com/foursquare/twofishes#hotfixes.

Hope this helps.

Rahul.

**Comment by jparise** [comment]
Like Foursquare, we only communicate with twofishes via internal RPC (Thrift). Network security is handled by AWS' security group mechanisms.

Our deployment artifact includes both the compiled twofishes server assembly as well as a copy of the index. I've toyed with the idea of having the deploy bootstrapping process grab the index from the network (e.g. S3), but we don't redeploy twofishes frequently enough for that to make much of a difference right now. It's a very stable service for us.

The actual deployment is coordinated using our in-house service deployment infrastructure. Until we open source that, there's unfortunately not much more to say about how those pieces work.
