### ISSUE TITLE
twofishes JSON endpoints don't set Content-Length header

### ISSUE THREAD

**Issue by eclesh** [foursquare/twofishes#87]
The twofishes JSON endpoints don't set the Content-Length header on responses. As a result, twofishes can't be used behind an Amazon ELB in HTTP-listening mode. All GET or POST requests result in 502 BAD_GATEWAY.

Looks like finagle didn't start setting Content-Length on all requests until https://github.com/twitter/finagle/pull/300 which is included in 6.22.0. Currently, twofishes builds with finagle-http 6.3.0 (https://github.com/foursquare/twofishes/blob/d609e0a37a0765e9a83dc73367c33586b67af681/project/GeocoderBuild.scala#L154).

**Comment by rahulpratapm** [comment]
Good point. Fixing now. Thanks.
