### ISSUE TITLE
Reverse goecoding providing results via JSON/HTTP interface but not Thrift

### ISSUE THREAD

**Issue by joshlk** [foursquare/twofishes#88]
If I try the following reverse geocode query using JSON/HTTP I get the following results:

GET http://localhost:8081/?ll=51.527022,0.047109
```
{
   "interpretations":[
      {
         "what":"",
         "where":"",
         "feature":{
            "cc":"GB",
            "name":"London",
            "displayName":"London",
            "woeType":7,
            ...

```

However, if I make the request using thrift (Python, pythrift), I get no results:
```python
import thriftpy
from thriftpy.rpc import make_client
from thriftpy.protocol import TCyBinaryProtocolFactory
from thriftpy.transport import TCyFramedTransportFactory

twofishes = thriftpy.load('geocoder.thrift')
client = make_client(twofishes.Geocoder, host='localhost', port='8080',
                     proto_factory=TCyBinaryProtocolFactory(),
                     trans_factory=TCyFramedTransportFactory())

r = twofishes.GeocodeRequest(ll=twofishes.GeocodePoint(51.527022, 0.047109))
client.geocode(r)
```

Output:
```python
GeocodeResponse(requestWktGeometry=None, interpretations=[], debugLines=None)
```

Any ideas?

**Comment by rahulpratapm** [comment]
Your GeocodePoint has lat/lng interchanged :)

**Comment by joshlk** [comment]
Sorry typo. But that's not the problem, it doesn't work once you swap them round (I've edited the previous post)

**Comment by rahulpratapm** [comment]
Oh, I believe you need client.reverseGeocode(r). geocode(r) does a forward geocode of an empty query string passing in ll as a latlng hint.

**Comment by joshlk** [comment]
Thanks that works :)

Why is it different endpoints in the Thrifit interface but the same for the HTTP interface?

**Comment by rahulpratapm** [comment]
I don't honestly know why :)

@blackmad ?
