### ISSUE TITLE
TwoFishes query is extremely slow

### ISSUE THREAD

**Issue by nguyenhoan1988** [foursquare/twofishes#92]
I am using the prebuilt version of TwoFishes
I run the server with the following command:

`java -jar server-assembly-0.84.9.jar --hfile_basepath 2015-03-05-20-05-30.753698`

then I try to increase the size of memory for the JVM, but the query is still too slow
`java -Xms2g -jar server-assembly-0.84.9.jar --hfile_basepath 2015-03-05-20-05-30.753698`

I monitor the machine, and for every query, it reads a lot of data from disk (a lot of iowait), is this the main problem? Is there anyway to load all index to memory for better querying time?

Could you help me on this problem? Thank you.

The time it took to query:
```
16:42:41.344
[pool-geocoder-thread-3] INFO  c.foursquare.twofishes.MapFileInput
 - reading key 'geonameid:765979' from index 'features' took 35981 milliseconds.
valueOpt is Some(258) bytes long

16:42:41.693
[pool-geocoder-thread-3] INFO  c.f.t.QueryLoggingGeocodeServerImpl 
 - {
        "query": "los",
        "woeHint": [ ], 
        "woeRestrict": [ ], 
        "allowedSources": [ ], 
        "responseIncludes": [ 7 ]
 }
took 36332 ms
```

**Comment by rahulpratapm** [comment]
You could pass `--warmup true`. See https://github.com/foursquare/twofishes/issues/60.
