### ISSUE TITLE
Support WKT_GEOMETRY_SIMPLIFIED and/or WKT_GEOMETRY for Continents (29)

### ISSUE THREAD

**Issue by smalleyd** [foursquare/twofishes#93]
Currently, returned features of WOE type 29 (continent) do not include polygon information (WKT_GEOMETRY). This means that for Europe, countries in the Middle East and Northern Africa are included in the bounding box. It would be helpful to at least provide the polygon for Europe if it's impractical to provider polygons for the other continents.

**Comment by rahulpratapm** [comment]
First off, this repo has been deprecated in favor of https://github.com/foursquare/fsqio/tree/master/src/jvm/io/fsq/twofishes

We don't include any polygons with the open source distribution. There are instructions for how to add shapes for the indexer to consume at https://github.com/foursquare/fsqio/blob/master/src/jvm/io/fsq/twofishes/docs/auxiliary_features_and_polygons.md

We don't currently readily have shapes for continents and don't really have a practical need for them either. You could consider synthesizing your own by stitching together country shapes.
