### ISSUE TITLE
Scala Client - Timing out

### ISSUE THREAD

**Issue by kyortsos** [foursquare/twofishes#94]
I'm using the Java/Thrift compiler to generate java code from `https://github.com/foursquare/twofishes/blob/master/interface/src/main/thrift/geocoder.thrift` and creating the client in Scala. I am unable to successfully receive a response from the server.

```
try {
      val transport = new TSocket(host, port)
      transport.setTimeout(10000) 
      transport.open()
      val protocol: TProtocol = new TBinaryProtocol(transport)
      val client = new Geocoder.Client(protocol)
      val req = new GeocodeRequest().setLl(new GeocodePoint(lat, lon))
      val results = Some(client.reverseGeocode(req))

      transport.close()

      results
    } catch {
      case e: Exception => println(e)
        None
    }
```
The code hangs on the `reverseGeocode` call, or times out when I set a timeout. Is this a common issue?

**Comment by rahulpratapm** [comment]
The twofishes server speaks finagle-thrift and uses the ThriftServerFramedCodec. My guess is that it will work if you wrap your socket in a TFramedTransport.

FYI, this repo has been deprecated in favor of https://github.com/foursquare/fsqio/tree/master/src/jvm/io/fsq/twofishes.

**Comment by kyortsos** [comment]
Thanks for the advice!
