### ISSUE TITLE
too many matches for san jose with autocomplete call

### ISSUE THREAD

**Issue by jinlin** [foursquare/twofishes#96]
http://tf-location2.jibeapply.com/?query=san+jose&woeRestrict=12,11,8,7&maxInterpretations=5&cc=US&lang=en&autocomplete=true results in the below error,  but searching for "San Jose CA" does works
http://tf-location2.jibeapply.com/?query=san+jose%20ca&woeRestrict=12,11,8,7&maxInterpretations=5&cc=US&lang=en&autocomplete=true.  the version we are using is 0.90.5. Any thoughts on this?  Any thoughts?

error: 
java.lang.Exception: too many matches
com.foursquare.twofishes.NameIndexHFileInput.getPrefix(HFileStorageService.scala:237)
com.foursquare.twofishes.HFileStorageService.getIdsByNamePrefix(HFileStorageService.scala:56)
com.foursquare.twofishes.AutocompleteGeocoderImpl$$anonfun$8.apply(AutocompleteGeocoderImpl.scala:202)
com.foursquare.twofishes.AutocompleteGeocoderImpl$$anonfun$8.apply(AutocompleteGeocoderImpl.scala:180)
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
scala.collection.immutable.Range.foreach(Range.scala:141)
scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
scala.collection.AbstractTraversable.map(Traversable.scala:105)
com.foursquare.twofishes.AutocompleteGeocoderImpl.generateAutoParsesHelper(AutocompleteGeocoderImpl.scala:180)
com.foursquare.twofishes.AutocompleteGeocoderImpl.generateAutoParses(AutocompleteGeocoderImpl.scala:254)
com.foursquare.twofishes.AutocompleteGeocoderImpl.doAutocompleteGeocode(AutocompleteGeocoderImpl.scala:277)
com.foursquare.twofishes.GeocodeRequestDispatcher$$anonfun$geocode$3.apply(GeocodeRequestDispatcher.scala:33)
com.foursquare.twofishes.GeocodeRequestDispatcher$$anonfun$geocode$3.apply(GeocodeRequestDispatcher.scala:33)
com.twitter.util.Duration$.inMilliseconds(Duration.scala:154)
com.twitter.ostrich.stats.StatsProvider$class.time(StatsProvider.scala:196)
com.twitter.ostrich.stats.StatsCollection.time(StatsCollection.scala:30)
com.foursquare.twofishes.GeocodeRequestDispatcher.geocode(GeocodeRequestDispatcher.scala:32)
com.foursquare.twofishes.GeocodeServerImpl$$anonfun$geocode$2.apply(GeocodeServer.scala:157)
com.foursquare.twofishes.GeocodeServerImpl$$anonfun$geocode$2.apply(GeocodeServer.scala:157)
com.twitter.util.Try$.apply(Try.scala:13)
com.twitter.util.ExecutorServiceFuturePool$$anon$2.run(FuturePool.scala:75)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
java.util.concurrent.FutureTask.run(FutureTask.java:166)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
java.lang.Thread.run(Thread.java:722)

**Comment by rahulpratapm** [comment]
The fix for this issue is included in 0.90.5 but has an indexer and server part. Was your index built with the new indexer as well?

Also, FYI, this project has migrated to https://github.com/foursquare/fsqio/tree/master/src/jvm/io/fsq/twofishes
